### ISSUE TITLE
Bulgarian ?

### ISSUE THREAD

**Issue by MartinSokolov15** [egorsmkv/vosk-ukrainian-demo#1]
Hi, i need to do this for Bulgarian. Any tips how to do it ?

**Comment by egorsmkv** [comment]
Is there a VOSK model for Bulgarian?

**Comment by MartinSokolov15** [comment]
No, but there is a ''Training your own model''' section, but i don't know how to use it. Did you try it?

**Comment by egorsmkv** [comment]
You can translate this instruction - https://github.com/egorsmkv/speech-recognition-uk/blob/master/vosk-model-creation/INSTRUCTION.md - and train own model for VOSK

Don't you have ability to use something else except VOSK?

**Comment by MartinSokolov15** [comment]
I'm searching for any options, but for now Vosk seems good choice. Any other suggestions ?

**Comment by egorsmkv** [comment]
I'd  suggest you to look on wav2vec2-bert
